language: python
matrix:
  include:
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - pytest -v -s --cache-clear -m local
