language: python
matrix:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c g-r-eg bgwas3
script:
  - bgwas3 --help
