{% set name = "bgwas3" %}
{% set version = "1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"
about:
  home: https://bgwas3.readthedocs.io
  license: GPL-3.0
requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - cgatcore
    - mako
