package:
  name: bgwas3
  version: 0.1
source:
  path: ..
build:
  number: 1
  script: python setup.py install
requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - argparse
    - ruffus
    - cgatcore
    - prokka
    - roary
    - pyseer
    - r-dplyr
    - r-readr
    - r-tidyr
    - r-stringr
    - r-tidytree
    - bioconductor-ggtree
