package:
  name: bgwas3
  version: 0.1
source:
  git_url: https://github.com/g-r-eg/bgwas3
build:
  number: 1
  script: python setup.py install
requirements:
  build:
    - python
    - numpy
  run:
    - python
    - ruffus
    - cgatcore
